### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'files/csv/ntosh.csv'

### ISSUE THREAD

**Issue by gbernal** [Mgajurel/speaker_recognition_major#1]
Hi there!,

First of thanks for sharing this project! when I follow this step 
run speaker-recognition.py $ python speaker-recognition.py
I get the error below. Any ideas as to why?

**
Wav files from: files/wav
Traceback (most recent call last):
  File "speaker-recognition.py", line 33, in <module>
    nn.train()
  File "/home/gbernal/dev/Speaker_recognition/src/nn/neural_network.py", line 81, in train
    np.savetxt(self.filepath+"/csv/"+audio[7:-4]+".csv", mfcc_feat, fmt='%.8f', delimiter=',')
  File "/home/gbernal/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1307, in savetxt
    open(fname, 'wt').close()
FileNotFoundError: [Errno 2] No such file or directory: 'files/csv/ntosh.csv'

**Comment by gbernal** [comment]
Nevermind I was running it with python 2.7 and it needs python 3.
All  good! .... for now :)
